# Generated by Django 4.2 on 2025-01-27 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgaeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='per_hourrate',
            field=models.IntegerField(default=500),
        ),
    ]
